Create Language Preference
awesome-academy/HN_Pra19_Android_Book_App pull request #10
Opened 2024-07-31 14:55 UTC by shinnosuke14202

## Related Tickets
- [#Task 78733: Content](https://edu-redmine.sun-asterisk.vn/issues/78733)
## WHAT
- Create language preference
## Evidence (Screenshot or Video)

## Review Checklist

Category | View Point | Description | Expected Reviewer Answer | Self review | Reviewer2 (name)
--- | --- | --- | --- | --- | ---
Conventions | Does the code follow Sun* coding style and coding conventions? | https://github.com/framgia/coding-standards/blob/master/eng/android/coding_convention_android_kotlin.md | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Redmine | Does the ticket follow Sun* Redmine working process?  | https://github.com/framgia/Training-Guideline/blob/master/WorkingProcess/redmine/redmine.md| YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Documentation | Is there any incomplete code? If so, should it be removed or flagged with a suitable marker like ‘TODO’? |  | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*

*(Other notes)*

2024-07-31 14:58 UTC, nang2002hv approved these changes

2024-07-31 16:39 UTC, nhikiu approved these changes

2024-08-01 01:52 UTC, gianghv-3456 requested changes
check my cmts

2024-08-01 01:52 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/screen/home/HomeFragment.kt
> +    private lateinit var dialog: Dialog
Sắp xếp lại thứ tự đi em

2024-08-01 01:52 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/screen/home/HomeFragment.kt
>                  adapter = novelsAdapter
quá nhiều tầng code lồng vào nhau, hạn chế sử dụng .apply khi không cần thiết em ơi

2024-08-01 01:52 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/screen/home/HomeFragment.kt
> +    }
Đây cũng vậy, quá nhiều tầng code, refactor đi em

2024-08-01 01:52 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/screen/home/HomeFragment.kt
> +        activity?.finish()
Clear backstack nữa em nha

2024-08-01 02:30 UTC, gianghv-3456 approved these changes
Oke

2024-08-01 02:30 UTC, merged