create ui, Fetch and display data
awesome-academy/HN_Pra19_Android_Book_App pull request #12
Opened 2024-08-01 07:46 UTC by nang2002hv

## Related Tickets
- [#Task 78572: Content](https://edu-redmine.sun-asterisk.vn/issues/78572)
## WHAT
Create UI for Search screen, Fetch and display data

## Evidence (Screenshot or Video)
![anh1ha](https://github.com/user-attachments/assets/c8cc3412-4723-4993-a6ba-03331f70df5e)

## Review Checklist

Category | View Point | Description | Expected Reviewer Answer | Self review | Reviewer2 (name)
--- | --- | --- | --- | --- | ---
Conventions | Does the code follow Sun* coding style and coding conventions? | https://github.com/framgia/coding-standards/blob/master/eng/android/coding_convention_android_kotlin.md | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Redmine | Does the ticket follow Sun* Redmine working process?  | https://github.com/framgia/Training-Guideline/blob/master/WorkingProcess/redmine/redmine.md| YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Documentation | Is there any incomplete code? If so, should it be removed or flagged with a suitable marker like ‘TODO’? |  | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*

*(Other notes)*

2024-08-01 07:49 UTC, shinnosuke14202 approved these changes

2024-08-01 07:52 UTC, nhikiu approved these changes

2024-08-01 09:15 UTC, gianghv-3456 requested changes
check my cmt

2024-08-01 09:15 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/screen/search/adapter/SearchAdapter.kt
> +        println("listBook: $listBook")
Không log ra kiểu này em ơi. Em dùng Log.d để có thể tự động bỏ log khi build bản release nhé

```suggestion
```

2024-08-01 09:15 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/screen/search/adapter/SearchAdapter.kt
> +            println("book1: $book")
```suggestion
```

2024-08-02 03:06 UTC, HVgiang86 requested changes

2024-08-02 03:06 UTC, HVgiang86 commented on app/src/main/java/com/example/book/screen/search/SearchFragment.kt
> +        searchText.setTextSize(TypedValue.COMPLEX_UNIT_SP, 14f)
Không hard code thế này. Em khai báo trong dimen và dùng getResource

2024-08-02 03:31 UTC, closed without merging