Create base API and queries
awesome-academy/HN_Pra19_Android_Book_App pull request #3
Opened 2024-07-22 06:55 UTC by shinnosuke14202

## Related Tickets
- [#Task 78131: Content](https://edu-redmine.sun-asterisk.vn/issues/78131)
## WHAT
- Create base API and queries
## Evidence (Screenshot or Video)

## Review Checklist

Category | View Point | Description | Expected Reviewer Answer | Self review | Reviewer2 (name)
--- | --- | --- | --- | --- | ---
Conventions | Does the code follow Sun* coding style and coding conventions? | https://github.com/framgia/coding-standards/blob/master/eng/android/coding_convention_android_kotlin.md | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Redmine | Does the ticket follow Sun* Redmine working process?  | https://github.com/framgia/Training-Guideline/blob/master/WorkingProcess/redmine/redmine.md| YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Documentation | Is there any incomplete code? If so, should it be removed or flagged with a suitable marker like ‘TODO’? |  | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*

*(Other notes)*

2024-07-23 07:00 UTC, nang2002hv approved these changes

2024-07-23 07:11 UTC, nhikiu approved these changes

2024-07-24 01:55 UTC, gianghv-3456 requested changes
Check my cmts plz

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/model/Book.kt
> +}
Viết thành một file Constant riêng em

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/BookRepository.kt
> +    }
Hàm chưa implement thì đặt TODO vào em

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/BookDataSource.kt
> +
```suggestion
```

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/BookDataSource.kt
> +
```suggestion
```

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/BookDataSource.kt
```suggestion
```

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/local/BookLocalDataSourceImpl.kt
> +
```suggestion
```

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/local/BookLocalDataSourceImpl.kt
> +
```suggestion
```

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/remote/BookRemoteDataSourceImpl.kt
> +
```suggestion
```

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/remote/fetchJson/GetJsonFromUrl.kt
> +
```suggestion
```

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/utils/Constant.kt
> +}
Constant không viết trong Object, viết thành Top-level nha em, vừa giúp code clean, vừa tối ưu ByteCode khi dịch chương trình

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/remote/fetchJson/ParseJson.kt
> +
```suggestion
```

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/remote/fetchJson/ParseJson.kt
> +
```suggestion
```

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/remote/fetchJson/ParseDataWithJson.kt
> +
```suggestion
```

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/remote/fetchJson/ParseDataWithJson.kt
> +
```suggestion
```

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/remote/fetchJson/ParseDataWithJson.kt
> +        val data = mutableListOf<Book>()
Không được để kiểu trả về là any, như vậy sẽ không đảm bảo type safety. Dùng Generic type đi em
```suggestion
    fun <T> parseJsonToListData(jsonObject: JSONObject?, keyEntity: String): T {
        val data = mutableListOf<Book>()
```

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/remote/fetchJson/GetJsonFromUrl.kt
> +@Suppress(("UNCHECKED_CAST"))
Phải Safecast, 
```suggestion
```

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/remote/fetchJson/GetJsonFromUrl.kt
> +    }
Class này cần phải SINGLETON, nếu không khi số lượng request của em lớn, sẽ sinh ra vô hạn các **"Single Thread"**

2024-07-24 01:55 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/remote/fetchJson/GetJsonFromUrl.kt
> +        executor.execute {
Nghiên cứu xây dựng 1 class chung để xử lý em nhé, em có thể sử dụng **HIGH-ORDER Function** để đưa các đoạn code cần xử lý vào

2024-07-25 14:33 UTC, ghost requested changes
Please check my comments

2024-07-25 14:33 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/remote/fetchJson/ParseDataWithJson.kt
> +    fun parseJsonToListData(jsonObject: JSONObject?, keyEntity: String): MutableList<Book> {
Data trả về từ Api là cố định, do đó dùng List thay cho MutableList, lên các tầng trên, nếu cần sử dụng MutableList ta sẽ convert sau

2024-07-25 14:33 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/data/repository/source/remote/fetchJson/ParseDataWithJson.kt
> +        return data
Em có thể dùng GSON nhé

2024-07-25 14:33 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/utils/BookEntry.kt
> +    const val SIMILAR_BOOKS = "similar_books"
Khai báo thành Top-level đi em

2024-07-25 14:33 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/utils/Constant.kt
> +const val BASE_API_KEY = "api-key=" + "e8ca81ce3a6244e4913423fcaf9f357c"
```suggestion
const val BASE_API_KEY =  "e8ca81ce3a6244e4913423fcaf9f357c"
```

2024-07-25 14:33 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/utils/Constant.kt
> +const val BASE_API_KEY = "api-key=" + "e8ca81ce3a6244e4913423fcaf9f357c"
Cấn quá em, để việc cộng xâu ở chỗ build URL đi, k nên để ở hằng số

2024-07-26 03:21 UTC, gianghv-3456 approved these changes
Nice!

2024-07-26 03:21 UTC, merged