Favorite screen: Create UI
awesome-academy/HN_Pra19_Android_Book_App pull request #6
Opened 2024-07-30 02:35 UTC by nhikiu

## Related Tickets
- [#Task 78451: Content](https://edu-redmine.sun-asterisk.vn/issues/78451)
## WHAT
- Favourite Screen - Create UI
## Evidence (Screenshot or Video)

## Review Checklist

Category | View Point | Description | Expected Reviewer Answer | Self review | Reviewer2 (name)
--- | --- | --- | --- | --- | ---
Conventions | Does the code follow Sun* coding style and coding conventions? | https://github.com/framgia/coding-standards/blob/master/eng/android/coding_convention_android_kotlin.md | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Redmine | Does the ticket follow Sun* Redmine working process?  | https://github.com/framgia/Training-Guideline/blob/master/WorkingProcess/redmine/redmine.md| YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
Documentation | Is there any incomplete code? If so, should it be removed or flagged with a suitable marker like ‘TODO’? |  | YES |<li>- [ ] yes</li>|<li>- [ ] yes</li>
## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*

*(Other notes)*

2024-07-30 02:37 UTC, shinnosuke14202 approved these changes

2024-07-30 02:37 UTC, nang2002hv approved these changes

2024-07-30 02:51 UTC, gianghv-3456 requested changes
Check my cmts

2024-07-30 02:51 UTC, gianghv-3456 commented on app/src/main/res/values/styles.xml
> +    </style>
```suggestion
    </style>
    
```

2024-07-30 02:51 UTC, gianghv-3456 commented on app/src/main/res/layout/item_favorite_book.xml
> +                android:text="0.0"
Nếu là default text, em phải đặt trong string resource.
Nếu là text để test lúc code Ui thì em phải sử dụng tools thay cho android (preview)
```suggestion
                tools:text="0.0"
```

2024-07-30 02:51 UTC, gianghv-3456 commented on app/src/main/java/com/example/book/screen/favorite/FavoritePresenter.kt
> +                    4.5,
Viết hàm trả về Data fake, không đặt trong onStart em

2024-07-31 02:05 UTC, gianghv-3456 approved these changes

2024-07-31 02:06 UTC, merged